export const buildFooter = (doc) => {

    doc
        .fontSize(10)
        .fillColor("gray")
        .text(
            "Generated by Aphelion Financial Operating System",
            50,
            doc.page.height - 50,
            {
                align: "center",
            }
        );

};