import {
    FaWallet,
    FaArrowTrendUp,
    FaArrowTrendDown,
    FaBullseye,
    FaShieldHalved,
    FaChartPie,
    FaChartLine,
    FaCoins,
    FaPiggyBank,
    FaHeartPulse,
    FaBuildingColumns,
    FaPercent,
    FaMoneyBillTrendUp,
    FaSackDollar,
    FaReceipt,
    FaCircleDollarToSlot,
} from "react-icons/fa6";

export {
    FaWallet,
    FaArrowTrendUp,
    FaArrowTrendDown,
    FaBullseye,
    FaShieldHalved,
    FaChartPie,
    FaChartLine,
    FaCoins,
    FaPiggyBank,
    FaHeartPulse,
    FaBuildingColumns,
    FaPercent,
    FaMoneyBillTrendUp,
    FaSackDollar,
    FaReceipt,
    FaCircleDollarToSlot,
};