import { sectionTitle } from "../pdf/components/section.js";
import { buildTable } from "../pdf/components/table.js";

const buildReportSignature = (
    doc,
    metadata
) => {

    doc.addPage();

    sectionTitle(
        doc,
        "Report Information"
    );

    buildTable(

        doc,

        [

            "Property",

            "Value",

        ],

        [

            [

                "Version",

                metadata.version,

            ],

            [

                "Engine",

                metadata.engine,

            ],

            [

                "Template",

                metadata.template,

            ],

            [

                "Generated",

                new Date(
                    metadata.generatedAt
                ).toLocaleString(),

            ],

        ]

    );

    doc.moveDown(4);

    doc

        .fontSize(12)

        .fillColor("#111827")

        .text(

            "Generated by",

            {

                align: "center",

            }

        );

    doc.moveDown();

    doc

        .fontSize(18)

        .fillColor("#2563eb")

        .text(

            "APHELION",

            {

                align: "center",

            }

        );

    doc.moveDown();

    doc

        .fontSize(11)

        .fillColor("#6b7280")

        .text(

            "Financial Operating System",

            {

                align: "center",

            }

        );

};

export const buildSignature = (
    doc,
    report
) => {

    buildReportSignature(
        doc,
        report.metadata
    );

};